name: pr

on:
  pull_request:

jobs:
  tsc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - run: tsc --pretty false --noEmit --emitDeclarationOnly false | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
