name: review
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - run: tsc --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
